### ISSUE TITLE
Question mark on iOS 14

### ISSUE THREAD

**Issue by drgs225305** [FortAwesome/react-native-fontawesome#75] opened 2020-10-02 05:20 UTC
My app was developed a years ago. It is on app store and google play store. My app display 'question mark'.

**Comment by dragoalexa97** [comment] 2020-10-02 05:27
![ios14](https://user-images.githubusercontent.com/49772943/94890837-038a8980-04b3-11eb-8c76-9cd4e032c71f.jpg)
![ios12](https://user-images.githubusercontent.com/49772943/94890848-0b4a2e00-04b3-11eb-96ec-b96496da0993.jpg)

**Comment by robmadole** [comment] 2020-10-02 14:50
@dragoalexa97 are you actually using this `react-native-fontawesome` component? This looks like a missing glyph when using a web font.

**Comment by JDJBSPL** [comment] 2020-10-05 14:00
> ![ios14](https://user-images.githubusercontent.com/49772943/94890837-038a8980-04b3-11eb-8c76-9cd4e032c71f.jpg)
> ![ios12](https://user-images.githubusercontent.com/49772943/94890848-0b4a2e00-04b3-11eb-96ec-b96496da0993.jpg)
> 
> It display icons correctly ios12 and below. on ios14, it does not work.

Same things happen to me too, Can't find any proper solution for it. Please Help

**Comment by robmadole** [comment] 2020-10-05 14:13
I need more information that a screenshot. What tooling is being used? What version of react-native-fontawesome?  Can you provide a reproducible test case because the question mark box usually indicates it's web fonts. If it is web fonts then it's not using react-native-fontawesome.

**Comment by MwareSolutons** [comment] 2020-10-06 11:22
Same here some work some do not.

**Comment by MwareSolutons** [comment] 2020-10-07 16:57
@dragoalexa97 Did you find a fix for this and if so could you please share ?

**Comment by MwareSolutons** [comment] 2020-10-07 17:11
@robmadole I have more information for you, it is a 100% IOS 14 issue i have tested on previous IOS versions and then it works fine for both iPhone and iPad, something in IOS 14 broke the SolidIcons hope this helps in solving it

**Comment by MwareSolutons** [comment] 2020-10-07 18:34
found a solution added this after the import and it started working 

SolidIcons._fontFamily = 'FontAwesome5Free-Solid';

**Closed** 2022-06-07 19:53 UTC
