### ISSUE TITLE
Invalid prop `style` of type `array` supplied to `FontAwesomeIcon`, expected `object`

### ISSUE THREAD

**Issue by genesy** [FortAwesome/react-native-fontawesome#40] opened 2019-12-13 19:50 UTC
**Describe the bug**
Warning message appears on simulator/console when clicking/tapping the icon when wrapped in a Touchable component

**Reproducible test case**
```
import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-native-fontawesome';
import { faHeart } from '@fortawesome/free-regular-svg-icons';
import { TouchableHighlight, View } from 'react-native'

export default () => (
  <View>
    <TouchableHighlight onPress={()=> {}} style={{padding: 50}}>
      <FontAwesomeIcon icon={faHeart}/>
    </TouchableHighlight>
  </View>
)
```
dep versions from package.json
```
    "@fortawesome/react-native-fontawesome": "^0.1.0",
    "@fortawesome/free-regular-svg-icons": "^5.12.0",
    "expo": "^36.0.0",
    "react": "16.9.0",
    "react-native": "0.61.4",
```

run this file on new react native project and the error should show when you tap

**Expected behavior**
No warning message spam

**Desktop (please complete the following information):**
 - Android simulator 8.1

**Additional context**
Was reported on a different github repo here
https://github.com/FortAwesome/react-fontawesome/issues/245

**Comment by yesterday24** [comment] 2019-12-17 15:06
I have the same error. I don't get the error on every screen. My expected behavior is nog warning message. The warning message shows up on iOS (11.4), not in android.

**Comment by likern** [comment] 2019-12-24 15:40
This is a cruicial bug, because if `styled-components` package is used (1,211,309 downloads/week) it automatically converts css properties to array of styles (at compile-time):

```ts
<FontAwesomeIcon
  css={`
    margin-left: 14px;
  `}
  icon={['fal', iconName]}
  size={24}
/>
```

**Comment by likern** [comment] 2020-01-28 23:25
For everyone for whoom this bug is cruicial might check out might forked project - https://github.com/breeffy/react-native-svg-icons

There is an added support for arrays. `styled-components` are working out of box.

**Comment by jdcookie** [comment] 2020-02-18 00:59
Seems like a temporary work around until a proper fix is done, it to wrap the FontAwesomeIcon component in a Fragment.

```
<TouchableHighlight onPress={() => {})>
  <>
    <FontAwesomeIcon icon={['fas', 'heart']} />
  </>
</TouchableHighlight>
```

I am using styled-components and was seeing the exact issue described above.

**Comment by robmadole** [comment] 2020-03-05 15:32
I'm going to work with @puremana to try and get his [PR merged](https://github.com/FortAwesome/react-native-fontawesome/pull/46)

**Comment by robmadole** [comment] 2020-03-06 16:16
0.2.3 released to support arrays (thanks @puremana)

**Closed by robmadole** 2020-03-06 16:16 UTC
