### ISSUE TITLE
Package has been ignored because it contains invalid configuration

### ISSUE THREAD

**Issue by droplessjake** [FortAwesome/react-native-fontawesome#118] opened 2022-03-24 14:53 UTC
**Describe the bug**
I'm seeing this error a lot recently across my project. I can't say for sure when it occurred but seems to have been with some recent package updates.

Error is below
```
warn Package @fortawesome/pro-light-svg-icons has been ignored because it contains invalid configuration. Reason: Cannot find module '/Users/runner/work/1/s/node_modules/@fortawesome/pro-light-svg-icons/package.json.js'
warn Package @fortawesome/pro-regular-svg-icons has been ignored because it contains invalid configuration. Reason: Cannot find module '/Users/runner/work/1/s/node_modules/@fortawesome/pro-regular-svg-icons/package.json.js'
warn Package @fortawesome/pro-solid-svg-icons has been ignored because it contains invalid configuration. Reason: Cannot find module '/Users/runner/work/1/s/node_modules/@fortawesome/pro-solid-svg-icons/package.json.js'
```
It seems to be hanging a lot of build commands and gets thrown during a lot of react native and yarn commands.

**Reproducible test case**
`react-native run-android`

**Expected behavior**
No warning should be thrown

**Desktop (please complete the following information):**
- "react-native": "0.66.3"
- "@fortawesome/fontawesome-svg-core": "6.1.1"
- "@fortawesome/pro-light-svg-icons": "6.1.1"
- "@fortawesome/pro-regular-svg-icons": "6.1.1"
- "@fortawesome/pro-solid-svg-icons": "6.1.1"
- "@fortawesome/react-native-fontawesome": "0.2.7"

Originally posted [on main FontAwesome repo](https://github.com/FortAwesome/Font-Awesome/issues/18844)

Seems like its looking for `package.json.js` paths when it should just be `package.json`..?

**Comment by DrOverbuild** [comment] 2022-06-09 22:02
I've been doing some investigation because this issue is still happening in v0.3.0. Seems to be caused by the presence of the `export` property in the warned libraries' package.json. I doubt anything can be done about it from this project.

**Comment by BasBuur** [comment] 2022-07-20 17:25
Any news on this issue? This is still happening and turns 3-minute builds into 45-minute builds and is therefore not usable.

**Comment by robmadole** [comment] 2022-07-28 16:42
This is fixed in 6.1.2. Please upgrade and let me know if that fixes things up.

**Comment by BasBuur** [comment] 2022-07-28 21:33
Thank you Rob. The warnings are gone, but the build time has remained extremely long for 6.1.2. Build times are fine with 5.15.0 and like x50 if not longer for 6.1.2. Same as [this person](https://github.com/FortAwesome/Font-Awesome/issues/18844#issuecomment-1198209520) it looks like.

**Comment by robmadole** [comment] 2022-07-28 21:43
@BasBuur how are you importing the icons? Have you reviewed [this section](https://fontawesome.com/v6/docs/web/use-with/react-native#same-icon-different-styles)?

**Comment by BasBuur** [comment] 2022-07-28 21:48
I wasn't aware of that caveat, thank you. Changing over our codebase to use this style of imports would be a **major** job though. Just curious, why was this issue not present with v5? Solely because of the amount of new icons?

I would really like to use some of the v6 icons so I guess I'll plan a day of icon-switcheroo-ing :)

**Comment by robmadole** [comment] 2022-07-28 21:53
Yeah sorry about forcing the change over. The problem is that react-native doesn't support tree-shaking. And your instinct is correct, it's just the sheer number of icons. We added a bunch in 6 and it's a blessing and a curse.

I will say just as an alternative you could use our Desktop Subsetter and create a subset of the icons that you use. One of the things that you will get from the subset (a .zip file) is a directory of JS packages. These are formatted _exactly_ like our full packages. You could install these and it would speed things up **tremendously**.

**Comment by BasBuur** [comment] 2022-07-28 22:03
Understood, thank you for the explanation!

I'm not the biggest fan of having local packages laying around and having to re-create the local package every time I want to use a new icon so I'll probably just bite the faBullet. Hold the faPhone - that icon doesn't exist? Oh well... Thanks again, I appreciate your time!

**Closed** 2022-07-29 22:06 UTC
